# .github/release.yml
# Configures GitHub's release notes generation

changelog:
  categories:
    - title: 🚀 Features
      labels:
        - feature
        - enhancement
    - title: 🐛 Bug Fixes
      labels:
        - bug
        - fix
    - title: 🧰 Maintenance
      labels:
        - chore
        - dependencies
        - documentation
    - title: Other Changes
      labels:
        - "*"

